# nome = input ('Qual é o seu nome?')
# idade = input ('Qual é a sua idade?')
# nasce = input ('Onde você nasceu?')
# data = input ('Quando você nasceu?')
# estado = input ('Qual seu estado civil?')
# casa = input ('Quando você vai se casar?')
# noivo = input ('Qual é o nome do noivo?')
# age = input ('Qual a idade do noivo?')
# print ('A',nome, 'possui',idade,'anos, nasceu na cidade de',nasce,', na data de' ,data,'. Está' ,estado,', pretendendo se casar em' ,casa,', com o' ,noivo,', que possui a idade de' ,age, 'anos.')
nome=input('Qual é o seu nome?')
print ('Bem vinda, '+nome)